GET HTTP://localhost:8080/api/clientes

###
GET HTTP://localhost:8080/api/clientes/2

###

POST HTTP://localhost:8080/api/clientes
Content-Type: application/json

{
    "nomeCliente": "Guilherme",
    "cpf": "12345678914",
    "email": "guilherme@gmail.com"
}

###

PUT HTTP://localhost:8080/api/clientes/4
Content-Type: application/json

{
    "nomeCliente": "Guilherme",
    "cpf": "12345678915",
    "email": "guilherme@gmail.com"
}

###

DELETE HTTP://localhost:8080/api/clientes/4





